title: Minimal
description: This is a minimal demo for jekyll-theme-acg.
author: Coder Zhao
lang: en-US

url:
baseurl: jekyll-theme-acg-minimal

theme: jekyll-theme-acg
acg:
  color: red
  categories: Categories
  tags: Tags
  about: About
  error: Page not found.
  github: coderzhaoziwei


defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

collections:
  posts:
    output: true
    permalink: /:collection/:title
