name: github-pages
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Jekyll
        run: |
          gem install jekyll bundler
          bundle exec jekyll --version
          bundle update
          bundle exec jekyll build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: _site
          target_branch: github-pages
          commit_message: "chore(deploy): deploy to github-pages branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
