name: github-pages
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle exec jekyll build
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: _site
          target_branch: github-pages
          commit_message: "chore(deploy): deploy to github-pages branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
